export const UPDATE_DISPLAY_NAME_CHANGE = "UPDATE_DISPLAY_NAME_CHANGE";
export const UPDATE_DISPLAY_NAME_START = "UPDATE_DISPLAY_NAME_START";
export const UPDATE_DISPLAY_NAME_SUCCESS = "UPDATE_DISPLAY_NAME_SUCCESS";
export const UPDATE_DISPLAY_NAME_FAIL = "UPDATE_DISPLAY_NAME_FAIL";
export const UPDATE_EMAIL_ADDRESS_CHANGE = "UPDATE_EMAIL_ADDRESS_CHANGE";
export const UPDATE_EMAIL_ADDRESS_START = "UPDATE_EMAIL_ADDRESS_START";
export const UPDATE_EMAIL_ADDRESS_SUCCESS = "UPDATE_EMAIL_ADDRESS_SUCCESS";
export const UPDATE_EMAIL_ADDRESS_FAIL = "UPDATE_EMAIL_ADDRESS_FAIL";

export const SIGN_UP_DISPLAY_NAME_CHANGED = "SIGN_UP_DISPLAY_NAME_CHANGED";
export const SIGN_UP_EMAIL_CHANGED = "SIGN_UP_EMAIL_CHANGED";
export const SIGN_UP_PASSWORD_CHANGED = "SIGN_UP_PASSWORD_CHANGED";
export const SIGN_UP_CONFIRM_PASSWORD_CHANGED = "SIGN_UP_CONFIRM_PASSWORD_CHANGED";
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export const LOGIN_EMAIL_CHANGED = "LOGIN_EMAIL_CHANGED";
export const LOGIN_PASSWORD_CHANGED = "LOGIN_PASSWORD_CHANGED";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const GAME_FORM_PROP_CHANGE = "GAME_FORM_PROP_CHANGE";
export const GAME_FORM_RESET = "GAME_FORM_RESET";
export const GAME_SELECTED = "GAME_SELECTED";

export const GAME_PERSIST_START = "GAME_PERSIST_START";
export const GAME_PERSIST_SUCCESS = "GAME_PERSIST_SUCCESS";
export const GAME_PERSIST_FAIL = "GAME_PERSIST_FAIL";

export const GAME_LOCATION_PERSIST_START = "GAME_LOCATION_PERSIST_START";
export const GAME_LOCATION_PERSIST_SUCCESS = "GAME_LOCATION_PERSIST_SUCCESS";
export const GAME_LOCATION_PERSIST_FAIL = "GAME_LOCATION_PERSIST_FAIL";

export const GAME_SCORE_PERSIST_START = "GAME_SCORE_PERSIST_START";
export const GAME_SCORE_PERSIST_SUCCESS = "GAME_SCORE_PERSIST_SUCCESS";
export const GAME_SCORE_PERSIST_FAIL = "GAME_SCORE_PERSIST_FAIL";

export const GAME_POST_PERSIST_START = "GAME_POST_PERSIST_START";
export const GAME_POST_PERSIST_SUCCESS = "GAME_POST_PERSIST_SUCCESS";
export const GAME_POST_PERSIST_FAIL = "GAME_POST_PERSIST_FAIL";

export const GAME_SET_PERSIST_START = "GAME_SET_PERSIST_START";
export const GAME_SET_PERSIST_SUCCESS = "GAME_SET_PERSIST_SUCCESS";
export const GAME_SET_PERSIST_FAIL = "GAME_SET_PERSIST_FAIL";

export const GAME_DELETE_START = "GAME_DELETE_START";
export const GAME_DELETE_SUCCESS = "GAME_DELETE_SUCCESS";
export const GAME_DELETE_FAIL = "GAME_DELETE_FAIL";

export const ADD_SAVED_GAME = "ADD_SAVED_GAME";
export const REMOVE_SAVED_GAME = "REMOVE_SAVED_GAME";

export const SAVED_GAMES_FETCH_SUCCESS = "SAVED_GAMES_FETCH_SUCCESS";
export const SAVED_GAMES_FETCH_FAIL = "SAVED_GAMES_FETCH_FAIL";

export const USER_GAMES_FETCH_START = "USER_GAMES_FETCH_START";
export const USER_GAMES_FETCH_SUCCESS = "USER_GAMES_FETCH_SUCCESS";

export const NEARBY_GAMES_FETCH_START = "NEARBY_GAMES_FETCH_START";
export const NEARBY_GAMES_FETCH_SUCCESS = "NEARBY_GAMES_FETCH_SUCCESS";

export const FAVORITE_GAMES_FETCH_START = "FAVORITE_GAMES_FETCH_START";
export const FAVORITE_GAMES_FETCH_SUCCESS = "FAVORITE_GAMES_FETCH_SUCCESS";
export const FAVORITE_GAME_FETCH_SUCCESS = "FAVORITE_GAME_FETCH_SUCCESS";

export const GAME_FETCH_START = "GAME_FETCH_START";
export const GAME_FETCH_SUCCESS = "GAME_FETCH_SUCCESS";

export const GAME_POSTS_FETCH_SUCCESS = "GAME_POSTS_FETCH_SUCCESS";
export const GAME_POSTS_FETCH_FAIL = "GAME_POSTS_FETCH_FAIL";
